### ISSUE TITLE
Boards point to the wrong AAT term

### ISSUE THREAD

**Issue by natuk** [linked-conservation-data/board-pilot-data#20]
The type of boards component in the LoC dataset point to the wrong AAT concept. At the moment it is:
`http://w3id.org/loc-vocab/5a30f6da-467b-4b60-9b0c-67f9aa31c01e exactMatch aat:300014616`
but it should be:
`http://w3id.org/loc-vocab/5a30f6da-467b-4b60-9b0c-67f9aa31c01e exactMatch aat:300202819`

**Comment by natuk** [comment]
OK, this is fixed now, but @acampagnolo if you can also fix the csv files and upload to the vocabulary repository, it would be great. I will leave this open until then.

**Comment by acampagnolo** [comment]
done and pushed to github

**Comment by natuk** [comment]
Hm, CSV file still missing, no? I am looking over here: https://github.com/linked-conservation-data/conservation-vocabularies/tree/master/align/loc-vocab--aat

**Comment by acampagnolo** [comment]
I'm not sure why, this is the commit: https://github.com/acampagnolo/conservation-vocabularies/commit/e4370fbc7895ff531089871b4acdc498948cf6c1

**Comment by natuk** [comment]
Ah, OK, it was in your forked vocabulary. I did a pull request and merge now.
